version: '2'
volumes:
  mongo-data:
    external: false
  redis-data:
    external: false

  nginx:
    restart: always
    build:
      context: ../..
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - "../server.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./upload:/usr/src/app/upload"
    volumes_from:
      - web

  redis:
    image: redis:alpine
    command: redis-server

  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  beanstalk:
    image: kusmierz/beanstalkd

  web:
    restart: always
    image: bootlegger/ourstory-server
    build: ../..
    depends_on: 
      - redis
      - mongo
      - beanstalk
    command: nodemon --watch api app.js # -- --verbose
    expose:
      - 1337
    volumes:
      - ../../config:/usr/src/app/config
      - "./upload:/usr/src/app/upload"
      - "../../api:/usr/src/app/api"
      - "../../assets:/usr/src/app/assets"
      - "../../views:/usr/src/app/views"