version: "2"
volumes:
  mongo-data:
    external: false
  redis-data:
    external: false

services:
  nginx:
    restart: on-failure
    build:
      context: ../..
      dockerfile: Dockerfile.nginx.local
    ports:
      # - "80:80"
      - "8845:80"
    volumes:
      - "../server.local.conf:/etc/nginx/conf.d/default.conf:ro"
      - "../bootlegger.dev.conf:/etc/nginx/vhost.d/default"
      - "./upload:/usr/src/app/upload"
      - "../../assets/transcription:/usr/src/app/assets/transcription"
    volumes_from:
      - web

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
      - ./backup:/backup
    ports:
      - "27017:27017"

  beanstalk:
    image: kusmierz/beanstalkd

  # worker:
  #   image: bootlegger/ourstory-worker
  #   depends_on:
  #     - mongo
  #     - beanstalk
  #   volumes:
  #     - "./upload:/usr/src/app/upload"

  web:
    restart: on-failure
    # image: bootlegger/ourstory-server:dev-staged
    build:
      context: ../..
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
      - mongo
      - beanstalk
    command: nodemon --watch api app.js -- --verbose
    environment:
      sails_LOGINCODE: "abcd"
      # sails_master_url: "http://10.10.10.1:8845"
      # sails_FAKES3URL: "http://10.10.10.1:8845/upload/"
      # sails_FAKES3URL_TRANSCODE: "http://10.10.10.1:8845/upload/transcode/upload/"
      # sails_master_url: 'http://10.10.10.1:8845'
    # command: node app.js # -- --verbose
    # expose:
    # - 1337
    volumes:
      - ../../config:/usr/src/app/config
      - "./upload:/usr/src/app/upload"
      - "../../api:/usr/src/app/api"
      - "../../assets:/usr/src/app/assets"
      - "../../views:/usr/src/app/views"
      - "../../tasks:/usr/src/app/tasks"
      - "../../transcription:/usr/src/app/transcription:ro"
      # - ../prod/.sailsrc:/usr/src/app/.sailsrc:ro
      # - ../prod/ssl:/usr/src/app/ssl:ro
      - ../../../ourstory-worker:/usr/src/ourstory-worker
      # - "../prod/.sailsrc:/usr/src/app/.sailsrc"
      - ./usbdrive:/usbdrive
      - ./redis:/redis
      # - /var/run/docker.sock:/var/run/docker.sock
