version: '2'
volumes:
  mongo-data:
    external: false
  redis-data:
    external: false

services:
  nginx:
    restart: on-failure
    build:
      context: ../..
      dockerfile: Dockerfile.nginx.local
    ports:
      - "80:80"
    volumes:
      # - "../server.conf:/etc/nginx/conf.d/default.conf:ro"
      - "../bootlegger.dev.conf:/etc/nginx/vhost.d/default"
      - "./upload:/usr/src/app/upload"
    volumes_from:
      - web

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '6379:6379'

  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  beanstalk:
    image: kusmierz/beanstalkd

  # worker:
  #   image: bootlegger/ourstory-worker
  #   depends_on:
  #     - mongo
  #     - beanstalk
  #   volumes:
  #     - "./upload:/usr/src/app/upload"

  web:
    restart: on-failure
    image: bootlegger/ourstory-server
    build:
      context: ../..
      dockerfile: Dockerfile.dev
    depends_on: 
      - redis
      - mongo
      - beanstalk
    command: nodemon --watch api app.js -- --verbose
    expose:
      - 1337
    volumes:
      - ../../config:/usr/src/app/config
      - "./upload:/usr/src/app/upload"
      - "../../api:/usr/src/app/api"
      - "../../assets:/usr/src/app/assets"
      - "../../views:/usr/src/app/views"
      - "../../ssl:/usr/src/app/ssl"
      # - "../../.sailsrc:/usr/src/app/.sailsrc"