---
name: default
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm

trigger:
  event:
    - tag

steps:
- image: golang:1.10.0-alpine
  commands:
    - echo -n "latest,$(git-buildnumber)" > .tags
- name: Build and Push  
  image: plugins/docker
  settings:
    repo: bootlegger/titan-compact
    dockerfile: docker/titan/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - TARGETPLATFORM=linux/arm/v7
    context: docker/titan/