debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
endpoint="unix://var/run/docker.sock"
watch=true
exposedByDefault = false
domain = "app.ourstory.dev"

[acme]
email = "tom.bartindale@monash.edu"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
acmeLogging = true